apiVersion: v1
kind: Service
metadata:
  name: app
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "my-backendconfig"}'
spec:
  ports:
    - name: app-port
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: app
    tier: frontend
  sessionAffinity: None
  type: ClusterIP
