apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  ports:
    - name: app-port
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: app
    tier: frontend
  sessionAffinity: None
  type: ClusterIP
